### ISSUE TITLE
Loupe::addDocuments throws Exception after updating from 0.7.0 to 0.8.0

### ISSUE THREAD

**Issue by ovenum** [loupe-php/loupe#116]
Thanks for all the work that went into Loupe and the recent releases! 🚀

After updating from from 0.7.0 to 0.8.0 i get the error message `An exception occurred while executing a query: Unable to execute statement: NOT NULL constraint failed: terms.idf` when trying to update a document in Loupes database via `Loupe::addDocuments`

The Error is thrown in Internal/Index/Indexer.php:92

Should i delete the Loupe DB and re-create the search index after updating Loupe to a new version? Or is Loupe expecting me to re-create DB and Search Index after each version change? I could not find any information regarding this in the docs or on the 0.8.0 release page.

**Comment by Toflar** [comment]
You can fix that by deleting and re-indexing, yes. Loupe has a helper for that which is `$loupe->needsReindex()` so you could automate your checks. Can you double check this returns `true` in your case?

**Comment by ovenum** [comment]
Thanks for looking into this @Toflar! `$loupe->needsReindex()` does return true for the installation in question. 
Recreating and re-indexing does work as expected. 

Will add a check for this and re-create DB and index if necessary.
