### ISSUE TITLE
How to escape parameters correctly

### ISSUE THREAD

**Issue by alexander-schranz** [loupe-php/loupe#16]
While implementing the filters here: https://github.com/schranz-search/schranz-search/blob/998f82023eff44efc8e6287f4daa87cdf5d5086e/packages/seal-loupe-adapter/src/LoupeSearcher.php#L80-L85

```
$searchParameters = SearchParameters::create()
    ->withQuery('search')
    ->withAttributesToRetrieve(['id', 'firstname'])
    ->withFilter("roles = 'Admin' AND departments = '" . $userInput . "')
    ->withSort(['lastname:asc'])
;
```

I'm asking what is the correct way to escape the parameters at this case? 

Should just `addslashes` used or how to avoid here injection / outbreak of the filter?

**Comment by Toflar** [comment]
I guess just quoting the `'` is enough. The filter value is quoted so injection should not be possible: https://github.com/loupe-php/loupe/blob/0.2/src/Internal/Filter/Ast/Operator.php#L30

But really, we need some tests with `O'Reilly` or so 😊

**Comment by Toflar** [comment]
See https://github.com/loupe-php/loupe/pull/54.
