### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Toflar** [loupe-php/loupe#2]
Hello designers,

If anybody cares about giving this project a nice logo, I would love to have one 😇 ❤️

**Comment by 1984logo** [comment]
@Toflar I came across your repository and I thought I'd make some proposals for your logo.
I made three:
- p1 evokes a magnifier with the letter L in it
- p2 shows a magnifier on a line of text
- p3 is more abstract ; it may evoke an eye or two overlapping shapes

Let me know if one of them works for you!

![Frame 1](https://github.com/loupe-php/loupe/assets/84827852/794a497d-982c-492d-94a6-50d1aa94bcb4)
![Frame 2](https://github.com/loupe-php/loupe/assets/84827852/6dcc6fcc-6bf7-4390-9611-5da105d0c809)
![Frame 3](https://github.com/loupe-php/loupe/assets/84827852/71667d46-4082-4223-8031-6ed1e007f5a9)

**Comment by doishub** [comment]
Hey, [we](https://github.com/oveleon)'ve also been working on giving you some suggestions. Almost forgot to post them. 😅

If you like any of them, or have any customization requests, feel free to let us know. I can also provide you with the raw file if you'd like.

Thanks for your superduper open source work! 💚

---

![Logo_Loupe](https://github.com/loupe-php/loupe/assets/48379929/6d4be08b-26ef-432e-a28c-f42a738e2f0a)

**Comment by Toflar** [comment]
Hey you lovely folks, thanks a lot for the submissions - love them! My personal fav is this one:

<img width="197" alt="Bildschirmfoto 2023-09-01 um 16 53 40" src="https://github.com/loupe-php/loupe/assets/481937/f23b1eff-5682-4faa-b2f9-6a5f7ed0960c">

Other opinions? 😊

**Comment by fkaminski** [comment]
My favorite is the draft from @doishub too!
Just for the purpose of alternative proposals, a quick kind of 3Dish variant ...

![logo-loupe-01](https://github.com/loupe-php/loupe/assets/7679799/5164c350-e9b9-4c00-acac-6dc6f5857a5f)

**Comment by Toflar** [comment]
Closed via https://github.com/loupe-php/loupe/pull/50.

Thanks everybody for the contributions ❤️
