### ISSUE TITLE
General error: 1 no such function: LN

### ISSUE THREAD

**Issue by AndiLeni** [loupe-php/loupe#38]
I get a `General error: 1 no such function: LN` error message when I try to add documents to the index.
However, `SQLite3::version()` reports the sqlite version 3.36.0.

**Comment by Toflar** [comment]
Then you compiled sqlite using the `--disable-math` flag. By default it should be enabled. But we should still fall back to the polyfill in this case.

**Comment by AndiLeni** [comment]
I am using php 8.1 on my windows 10 system. The php runtime is from https://windows.php.net/ if this helps.

**Comment by Toflar** [comment]
Can you check if https://github.com/loupe-php/loupe/pull/40 fixes your issue?

**Comment by AndiLeni** [comment]
@Toflar Yes, this seems to work :-)

**Comment by Toflar** [comment]
Released as 0.3.1.
