### ISSUE TITLE
Stop words

### ISSUE THREAD

**Issue by soderlind** [loupe-php/loupe#61]
Are stop words supported? If yes, how do I add them?

**Comment by Toflar** [comment]
Not yet, that would be a nice addition 😊

**Comment by soderlind** [comment]
For inspiration :)
https://www.meilisearch.com/docs/reference/api/settings#stop-words

**Comment by Toflar** [comment]
Yeah I know that feature, it could be easily added to our `Configuration`, we don't need to store them anywhere imho. PR is welcome!

**Comment by Toflar** [comment]
Thanks to @daun, this will be possible in 0.9: https://github.com/loupe-php/loupe/pull/107 🥳
