### ISSUE TITLE
string as id

### ISSUE THREAD

**Issue by AndiLeni** [loupe-php/loupe#65]
Hello @Toflar ,

As far as I can see, the addDocument() function expects the id attribute to be an integer.
Do you have any recommendations how to handle documents which have a string as their unique identifier?
F.e. I am indexing website contents and the unique attribute is the URL of those sites. 

Thanks and kind regards

**Comment by Toflar** [comment]
What makes you think that? All type hints are `int|string` for IDs? :)

**Comment by Toflar** [comment]
Please provide a way how I can reproduce the error, otherwise I cannot help you :)

**Comment by AndiLeni** [comment]
I will check if I can reproduce the error and create a minimal example
