### ISSUE TITLE
Typo and cyrillyc symbols

### ISSUE THREAD

**Issue by petrovich24** [loupe-php/loupe#73]
When typo is enabled and text contain cyrillyc symbols levenshtein function convert them to ? chars.
For example word "пожар" converted to "?????" and word "тепло" converted to "?????"
In that case both words founding in result set.

This is because internal levenshtein function uses _\Toflar\StateSetIndex\Levenshtein::distance_ function, that executes next code:
`$string1 = mb_convert_encoding($string1, 'ASCII', 'utf8');`
all non ascii symbols converted to ? 

Why not use php internal levenshtein function directly?

**Comment by Toflar** [comment]
> Why not use php internal levenshtein function directly?

Because it's not multibyte capable. Can we close this in favor of https://github.com/Toflar/state-set-index/pull/6?

**Comment by petrovich24** [comment]
yes, of course
