### ISSUE TITLE
Add support for negative queries

### ISSUE THREAD

**Issue by Toflar** [loupe-php/loupe#95]
- Support `-foobar` to exclude documents that contain `foobar`
- Support `-"foo bar"` to exclude documents that contain the entire `"foo bar"` string

**Comment by daun** [comment]
@Toflar I think I'll give this a try in the next days — seems like a nice exercise to get to know the internals :)

**Comment by daun** [comment]
Suggested implementation at #104

**Comment by Toflar** [comment]
Coming in v0.8 thanks to @daun! ❤️
