### ISSUE TITLE
Query terms are ORed instead of ANDed

### ISSUE THREAD

**Issue by Toflar** [loupe-php/loupe#96]
When you search for `pilot case` you should only find documents where both terms appear. Currently both, documents with only `pilot` and only `case` are found.

**Comment by Toflar** [comment]
This requires basically a rewrite of half of the search engine. So that's for someday when there's a lot of time - until then, Loupe will search all documents that have either/or terms.

**Comment by Toflar** [comment]
Hmm, not even sure anymore if that's what we want anyway. If this would be implemented, there would be no relevance ranking anymore. If all of the query terms have to match, the relevance would be `1.0` everywhere. I think this is nonsense after all.

**Comment by discordier** [comment]
So in the end the "and" implies a filter on relevance of 1.0 as workaround?

**Comment by Toflar** [comment]
Yes. This is not a bug anyway. I won't change the Or behavior because it's correct. But I'll close and reply in detail when I have more time.

**Comment by discordier** [comment]
My quick test tells me a different story if I did not make a grave mistake (very possible).

I have a text indexed, which has three occurrences of the word "active" in one attribute.
When now searching for `active`, I get the following hit:
```
array (
  'id' => 366,
  'question' => '[...]',
  'answer' => '[...]',
  'summary' => '-',
  '_rankingScore' => 0.38491,
  '_formatted' => array (
    'id' => 366,
    'question' => '[...]',
    'answer' => '[...]activate[...]activation[...]actions[...]',
    'summary' => '-',
    '_rankingScore' => 0.38491,
  ),
  '_matchesPosition' => array (
    'answer' => array (
      0 => array (
        'start' => 1375,
        'length' => 8,
      ),
      1 => array (
        'start' => 1394,
        'length' => 10,
      ),
      2 => array (
        'start' => 1490,
        'length' => 7,
      ),
    ),
  ),
)
```

We see, we get 3 hits in the text (levenshtein distance allows for these hits).
The ranking score is here 0.3.

If I now search for `active activate` (same keyword as above AND a direct match from above result), I now get:
```
array (
  'id' => 366,
  'question' => '[...]',
  'answer' => '[...]',
  'summary' => '-',
  '_rankingScore' => 0.30548,
  '_formatted' => array (
    'id' => 366,
    'question' => '[...]',
    'answer' => '[...]activate[...]activation[...]actions[...]',
    'summary' => '-',
    '_rankingScore' => 0.30548,
  ),
  '_matchesPosition' => array (
    'answer' => array (
      0 => 
      array (
        'start' => 1375,
        'length' => 8,
      ),
      1 => array (
        'start' => 1394,
        'length' => 10,
      ),
      2 => array (
        'start' => 1490,
        'length' => 7,
      ),
    ),
  ),
)
```
Now the score has dropped to 0.30, despite the fact that the result matches better (personal opinion - obviously the algorithm disagrees here).

Final test, search for `activate` (exact word match here):
```
array (
  'id' => 366,
  'question' => '[...]',
  'answer' => '[...]',
  'summary' => '-',
  '_rankingScore' => 0.34976,
  '_formatted' => array (
    'id' => 366,
    'question' => '[...]',
    'answer' => '[...]activate[...]activation[...]actions[...]',
    'summary' => '-',
    '_rankingScore' => 0.34976,
  ),
  '_matchesPosition' => array (
    'answer' => array (
      0 => array (
        'start' => 1375,
        'length' => 8,
      ),
      1 => array (
        'start' => 1394,
        'length' => 10,
      ),
      2 => array (
        'start' => 1490,
        'length' => 7,
      ),
    ),
  ),
)
```
Best score so far, as expected, but far away from the desired 1.0 you advised (even without AND here).

I fail to see a way to determine which result is better (from an user perspective) here.

For context, the search parameters here were:
```
\Loupe\Loupe\SearchParameters::__set_state(array(
   'attributesToHighlight' => array (
    0 => 'answer',
    1 => 'question',
    2 => 'summary',
  ),
   'attributesToRetrieve' => array (
    0 => 'answer',
    1 => 'id',
    2 => 'question',
    3 => 'summary',
  ),
   'attributesToSearchOn' => array (
    0 => '*',
  ),
   'filter' => '',
   'highlightEndTag' => '</info>',
   'highlightStartTag' => '<info>',
   'hitsPerPage' => 10,
   'page' => 1,
   'query' => 'activate',
   'showMatchesPosition' => true,
   'showRankingScore' => true,
   'sort' => array (
    0 => '_relevance:desc',
  ),
))
```
The configuration:
```
\Loupe\Loupe\SearchParameters::__set_state(array(
   'attributesToHighlight' => array (
    0 => 'answer',
    1 => 'question',
    2 => 'summary',
  ),
   'attributesToRetrieve' => array (
    0 => 'answer',
    1 => 'id',
    2 => 'question',
    3 => 'summary',
  ),
   'attributesToSearchOn' => array (
    0 => '*',
  ),
   'filter' => '',
   'highlightEndTag' => '</info>',
   'highlightStartTag' => '<info>',
   'hitsPerPage' => 10,
   'page' => 1,
   'query' => 'activate',
   'showMatchesPosition' => true,
   'showRankingScore' => true,
   'sort' => array (
    0 => '_relevance:desc',
  ),
))
```

**Comment by Toflar** [comment]
Finally I get to reply here, sorry 😊 So the reason why I think `OR` is correct is because Meilisearch does exactly the same. You can play around with it yourself but basically if you take one of the demos (https://music.meilisearch.com) and you search for `pink floyd` you will also find `Lady Pink`. The word `floyd` is not present there. It's just on page 40 or so, so not relevant at all. But it still matches the query.

But what is different and what is of course better is that the ranking is better. Due to different factors:

- MeiliSearch favors documents that match all terms. So documents with both, `pink` and `floyd` are ranked higher.
- MeiliSearch also favors proximity. So a document with `pink floyd` is ranked higher than a document with `a pink umbrella was given to Floyd`.

Both of which absolutely make sense.
Loupe, however, only works with a simple TF/IDF algorithm. And it is very well possible that this one is buggy too - I would appreciate any help there 😊

**Comment by discordier** [comment]
I'll check it out - trying to install it brought me #99 (installing in Contao 4.13 here - therefore no dbal 4.x).

**Comment by Toflar** [comment]
`develop` now contains both, new support for `$searchParameters->withRankingScoreThreshold()` and the new ranking algorithm. I'm closing this issue because I'm pretty sure you'll get better results now :)
